{% set name = "pyproprop" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 489e66db2879674ec944929258ea064c56ed24834dba46aa3623534ed4891f20

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy >=1.17
    - regex >=2020.4.4
    - titlecase >=2.2
    - typing >=3.7
    - sympy >=1.6

test:
  imports:
    - pyproprop

about:
  home: https://github.com/brocksam/pyproprop
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Defensive DRY Python properties without the boilerplate
  description: |
    Pyproprop lets you write classes that contain lots of repetitive properties 
    which implement idioms such as type checking, bounds checking, type casting, 
    method applications etc. with ease and in a DRY manner.
  doc_url: https://pyproprop.readthedocs.io/
  dev_url: https://github.com/brocksam/pyproprop

extra:
  recipe-maintainers:
    - brocksam
    - jackirvine97
